### ISSUE TITLE
problem at running the project with visual studio... please help!

### ISSUE THREAD

**Issue by itapi** [humphd/VncSharp#15]
i've just downloaded the project and launched with visual studio this is what i get:
![image](https://cloud.githubusercontent.com/assets/10478457/9392976/18adf862-4788-11e5-9c12-6508cd66f89f.png)

any idea why is it like this?

**Comment by Fabzien** [comment]
Maybe it's a little bit late but check your references.

Do you have ?

System.Windows.Forms
System.Drawing

**Comment by AzeeSoft** [comment]
I have the same issue. Please help!
