### ISSUE TITLE
Help to Use VncSharp Server As Windows Service 

### ISSUE THREAD

**Issue by macompengin** [humphd/VncSharp#16]
hello 
i want to use VncSharp Server As Windows Service , to always  listen to Requests to Remote any Host 
i Run the server and client successfully in Windows App in C#. but when i convert server side to windows service and request a remote to service  i can not see any windows form in VncSharp client (in VncSharp Remote Desktop control)!!! but in Service EventLog file i can Trace That Procees is running and all PointerEvent ,or keyboardEvent is logged to that file but i cant see any thing !!
can you Help me to Find Whats Wrong With my Code Please?!

**Comment by macompengin** [comment]
is it possible to use VNCsharp server side as windows services?
if yes what's wrong with my service?

**Comment by kmscode** [comment]
@macompengin From the readme "VncSharp is a VNC Client Library". So I don't think it's very likely that you'll be able to use this to run a VNC server. There are free VNC servers available.
