### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by OECODE** [humphd/VncSharp#20]
Hi,
If everything is good, and VNC is showing remote panel, but if I then disconnect the ethernet cable, it takes very long time, before the .ConnectionLost event raises.  ~15 sec.
Is it possible to set a timeout to a shorter period ~2 seconds..?
Someone with same problem..?

**Comment by zzincubus** [comment]
Within the latest code there are now two timeout consts (SEND_TIMEOUT & RECV_TIMEOUT), you may get the required timeout by changing the values currently defined (15000ms).

RfbProtocol.cs is the file where these two constants are set (the values are in milliseconds).

**Comment by humphd** [comment]
Closing based on #31
