### ISSUE TITLE
Issues connecting to TightVNC Server

### ISSUE THREAD

**Issue by allendukes** [humphd/VncSharp#30]
I get the following error when I call Connect():

"Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host."

The example works, but my code doesn't?

Any help would be greatly appreciated!

**Comment by humphd** [comment]
Maybe throw your actual code (just the bit calling `Connect()`) in here so people can see it?  Hard to know without more data.

**Comment by allendukes** [comment]
I also get:

An unhandled exception of type 'System.NullReferenceException' occurred in VncSharp.dll
Additional information: Object reference not set to an instance of an object.

When I tried to add the example Forms to my test project :-(

**Comment by humphd** [comment]
What is the call stack on that exception?  Can you paste it in?

**Comment by allendukes** [comment]
Stack Trace: 
"   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)\r\n   at VncSharp.RemoteDesktop.SetupDesktop()\r\n   at VncSharp.RemoteDesktop.Initialize()\r\n   at VncSharp.RemoteDesktop.Connect(String host, Int32 display, Boolean viewOnly, Boolean scaled)\r\n   at VncSharp.RemoteDesktop.Connect(String host, Boolean viewOnly, Boolean scaled)\r\n   at COG_Pack.Devices.TCD.form.connectToolStripMenuItem_Click(Object sender, EventArgs e) in C:\\Programming\\COG_Pack\\Devices\\COG_Pack.Devices.TCD\\VncSharpExampleForm.cs:line 65"

COG_Pack.Devices.TCD is Project specific

**Comment by allendukes** [comment]
I think it's a .NET Framework version issue.

**Comment by allendukes** [comment]
Yep, It's a .NET Framework version issue. My Original dll was targeting .NET 2.0. I downloaded the master branch from here and recompiled for 4.5.2 and re-referenced. However, no the connection keeps dying. :-/

**Comment by humphd** [comment]
There is an idle timeout setting, which was recently changed by @zzincubus.  I'm not sure that it's related to your issue, though.

**Comment by humphd** [comment]
@allendukes if you want to test to see if it's related to this change, you could try downloading https://github.com/humphd/VncSharp/archive/b275252633378934c999460ad3a63fe41f74ae91.zip, which was the commit just before that timeout change landed.

**Comment by zzincubus** [comment]
@allendukes i am using .NET 4.5.2 with the latest code. Could you try commenting the following code to see if it resolves your issue?

VncClient.cs (around line 425) ==>

        //[DefaultValue(false)]
        //[Description("True if view-only mode is desired (no mouse/keyboard events will be sent)")]
        ///// <summary>
        ///// True if view-only mode is desired (no mouse/keyboard events will be sent).
        ///// </summary>
        //public bool ViewOnly
        //{
        //    get { return vnc.IsViewOnly; }
        //    set { SetInputMode(value); }
        //}

However if using the version without the timeout code changes corrects your issue let me know so I can take a look into it.

**Comment by allendukes** [comment]
Yep, The View only code definitely raises some issues. My Designer complained about View Only and broke the project. Local Git to the rescue, but the ViewOnly property seems to cause some issues. :-/

**Comment by zzincubus** [comment]
Did the previous code correct the Connect failures, or was it still present?

**Comment by allendukes** [comment]
Commenting out the ViewOnly code brought the Designer back together (after a bit of hackery). Setting ViewOnly in the Designer definitely seems to be the culprit. I believe it complained that the setter calling 'SetInputMode' complained that 'vnc' was null in 'SetInputMode'. All's working now!

**Comment by zzincubus** [comment]
@humphd I had the same issue (but forgot I had made the above change/comment out to correct it). Within VS 2017 and a .NET 4.5.2 project the VncSharp component causes an issue within the designer (null reference). So no actual code has been executed yet.

I'll take a look to see if I can correct this behaviour without commenting out the offending ViewOnly property (should note that ViewOnly functionality still works when set on the connect call).

**Comment by zzincubus** [comment]
@humphd @allendukes - Pull request added to correct the ViewOnly issue. Also some other minor improvements following the BitsPerPixel commit. Please let me know what indents need to be corrected, as the code seems to use both spaces and tabs for indenting :-)

**Comment by humphd** [comment]
Closing based on #31.  Thanks @zzincubus!
