### ISSUE TITLE
There are some C#7.0 that can't be built in before vs 2015

### ISSUE THREAD

**Issue by masterjian** [humphd/VncSharp#32]
You know, not all the ape use the newest VS version.  :-)

VncClient.cs，Line 391 And Line 394

rfb.ReadFramebufferUpdateRectHeader(out Rectangle rectangle, out int enc);

// Build a derived EncodedRectangle type and pull-down all the pixel info
var er = factory.Build(rectangle, enc);

**Comment by humphd** [comment]
Looks like this went in with https://github.com/humphd/VncSharp/commit/3c0785ec88736b084b46edd91bd8f510b8fe6a83, cc @kmscode.

Did you want to do a PR to make it work in your version, @masterjian?
