### ISSUE TITLE
'Invalid subencoding value' when connecting to a remote VNC printer

### ISSUE THREAD

**Issue by Fabzien** [humphd/VncSharp#33]
Dear team,

First thank for this awesome tool. 

I have an issue when trying to remotely connect to a VNC server on a Lexmark printer.

VncSharp raise the following exception:

**System.Exception : 'Invalid subencoding value' in "ZlreRectangle.cs" line 52**

```
var subencoding = rfb.ZrleReader.ReadByte();

if (subencoding >= 17 && subencoding <= 127 || subencoding == 129)
throw new Exception("Invalid subencoding value");
```

**subencoding** value is 34 in my case.

Remote form stay black and nothing happen.

Any idea why could cause this behavior ?

Fabzien.

**Comment by humphd** [comment]
I don't really maintain this anymore, and to be honest, I can't remember all the details.  However, re-reading https://tools.ietf.org/html/rfc6143#section-7.7.6, I note the following about subencoding values:

>   17 to 126:  Unused.  (Packed palettes of these sizes would offer no
>   advantage over palette RLE).

and

> The tiles are encoded in exactly the same way as TRLE, except that
> subencoding may not take the values 127 or 129, i.e., palettes cannot
> be reused between tiles.

I'd say your printer is operating outside what the spec expects.  If you change the code to allow for `34`, does it work?

**Comment by Fabzien** [comment]
Thank for the quick answer !

What do you mean by allowing 34 ?

I commented:
``if (subencoding >= 17 && subencoding <= 127 || subencoding == 129)
throw new Exception("Invalid subencoding value");``

Still the same result but I have some `'System.IndexOutOfRangeException'` exceptions.

**Comment by humphd** [comment]
I mean alter the code to allow `34` to get through.  If you commented it out, that's a fair test.

It sounds like this is not going to work, unless you can trace those exceptions and see if you can hack around them.  I'd say that your printer is not doing the right thing, based on the spec.

**Comment by Fabzien** [comment]
<pre>
private void ReadZrlePlainRLEPixels(int tw, int th, int[] tileBuffer)
		{
			var ptr = 0;
			var end = ptr + tw * th;
			while (ptr < end) {
				var pix = preader.ReadPixel();
				var len = 1;
				int b;
				do {
					b = rfb.ZrleReader.ReadByte();
					len += b;
				} while (b == byte.MaxValue);

				while (len-- > 0) tileBuffer[ptr++] = pix;
			}
		}
</pre>

The `'System.IndexOutOfRangeException'` is at `'while (len-- > 0) tileBuffer[ptr++] = pix;'`

I also think printer is out of spec. I gonna try to hack around. If I am successful, I will post solution here.

**Comment by Fabzien** [comment]
I captured network packets between "TightVNC" and this device

![image](https://user-images.githubusercontent.com/26408860/49236643-d5dae200-f3fc-11e8-8af5-09440b2c2371.png)

So I tried to change TILE value to:

<pre>    
// Old
//private const int TILE_WIDTH = 64;
//private const int TILE_HEIGHT = 64;
// Hack
private const int TILE_WIDTH = 480;
private const int TILE_HEIGHT = 272;
</pre>

Still have OutOfRange exception. Maybe "Bits per pixel" is not the same ?

**Comment by Fabzien** [comment]
I have the following difference between VncSharp and TightVNC:

VncSharp:
![image](https://user-images.githubusercontent.com/26408860/49237369-5b12c680-f3fe-11e8-8d5e-4d669e583c00.png)

TightVNC:
![image](https://user-images.githubusercontent.com/26408860/49237400-6c5bd300-f3fe-11e8-9444-f94fe1d57f12.png)

I will working on that.

**Comment by humphd** [comment]
Interesting.  Look at https://github.com/TurboVNC/tightvnc/blob/a235bae328c12fd1c3aed6f3f034a37a6ffbbd22/vnc_unixsrc/vncviewer/tight.c#L86-L126, and you can see them doing some conversions for the 32bpp case to alter those same values.  Probably we need something similar.

**Comment by Fabzien** [comment]
@humphd 
I had this to Framebuffer.cs at line 253

            else if((bitsPerPixel == 32) && (depth == 24))
            {
                buffer.BitsPerPixel = 32;
                buffer.Depth = 24;
                buffer.BigEndian = b[2] != 0;
                buffer.TrueColour = true;
                buffer.RedMax = 255;
                buffer.GreenMax = 255;
                buffer.BlueMax = 255;
                buffer.RedShift = 16;
                buffer.GreenShift = 8;
                buffer.BlueShift = 0;
            }
And in ZrleRectangle.cs at line 51 change to

                    if (subencoding >= 17 && subencoding <= 127 || subencoding == 129 || subencoding == 131)
                        throw new Exception("Invalid subencoding value");

it's seems to work !

![image](https://user-images.githubusercontent.com/26408860/49589173-fc52cd00-f968-11e8-86f5-9516df53f338.png)

Many thanks for you help !

**Comment by Fabzien** [comment]
Just to add I initialize with:

            remoteDesktop1.VncPort = 5901;
            remoteDesktop1.BitsPerPixel = 32;
            remoteDesktop1.Depth = 24;
            remoteDesktop1.Connect("192.168.26.182");

**Comment by humphd** [comment]
@Fabzien did you want to create a PR to make this change to the code?  Happy to guide you if you need any help.  Let me know.

Glad you got your stuff working!
