### ISSUE TITLE
error when connecting to VNC server

### ISSUE THREAD

**Issue by ricksu** [humphd/VncSharp#34]
When I tried to connect to VNC server( Windows version 6.4.0), I got the  error dialog, saying "Unable to connect to the server. Error was: Only versions 3.3, 3.7, and 3.8 of the RFB Ptotocol are supported.. 
Check that a VNC host is running there."

Can anyone help?  Thanks a lot.

**Comment by humphd** [comment]
What version of VNC's RFB protocol is the server sending in the code?  If it's not one of the ones listed, it's not one we support.

**Comment by ricksu** [comment]
The server is "VNC server", as the picture shown below. I think it should running RFB protocol 3.8.

![vnc](https://user-images.githubusercontent.com/1207951/52033483-0f94aa00-2560-11e9-9e10-5620c934d63c.png)

thanks.

**Comment by humphd** [comment]
I'm not sure.  Without attaching a debugger and seeing which protocol version is being sent, I don't know.
