### ISSUE TITLE
Force Color Display

### ISSUE THREAD

**Issue by gashlin** [humphd/VncSharp#9]
I am having trouble trying to figure out how to change its color display. So if it connects to a viewer I can tell it to connect in 8 bit or 16 bit. I have tried adjusting the RGB but it really did not work. 

Any help would be great to achomplish this. I want to use this viewer over low bandwidth.

**Comment by Fabzien** [comment]
For test purpose only, you can try to edit buffer function in FramBuffer.cs:

`public static Framebuffer FromPixelFormat(byte[] b, int width, int height)`

Example:

```
            // TEST
            buffer.BitsPerPixel = (int)b[0];
            buffer.Depth = (int)b[1];
            buffer.BigEndian = false; // false for eBX
            buffer.TrueColour = (b[3] != 0);
            buffer.RedMax = (int)(b[5] | b[4] << 8);
            buffer.GreenMax = (int)(b[7] | b[6] << 8);
            buffer.BlueMax = (int)(b[9] | b[8] << 8);
            buffer.RedShift = 16; // 16 for eBX
            buffer.GreenShift = 8; // 8 for eBX
            buffer.BlueShift = 0; // 0 for eBX
            // Last 3 bytes are padding, ignore	
```

**Comment by zzincubus** [comment]
Is it possible to force a connection to 8-bit, as the device I am connecting to is on a very slow network. The above example does not appear to make any difference.

**Comment by zzincubus** [comment]
I have found that this is possible and I have made some changes to the the code. Please find updated files attached to support differing BitsPerPixel and Depth settings (rename file extension to .cs from .txt). Leave values as '0' to use server given values.

[Framebuffer.txt](https://github.com/humphd/VncSharp/files/1734888/Framebuffer.txt)
[RemoteDesktop.txt](https://github.com/humphd/VncSharp/files/1734889/RemoteDesktop.txt)
[RfbProtocol.txt](https://github.com/humphd/VncSharp/files/1734890/RfbProtocol.txt)
[VncClient.txt](https://github.com/humphd/VncSharp/files/1734891/VncClient.txt)

**Comment by humphd** [comment]
@zzincubus do you want to just send this as a pull request?  Let me know if you need help.

**Comment by zzincubus** [comment]
@humphd I apologise, first time using GitHub. I have created a branch but I am unable to publish it. Is this the correct method of then creating a pull request?

**Comment by humphd** [comment]
@zzincubus don't apologize, welcome to github!  Here's what you want to do:

1. Fork my repo into your account on GitHub
2. Clone *your* new forked repo onto your local machine: `git clone git@github.com:zzincubus/VncSharp.git`
3. Make a new branch in your repo for your changes: `git checkout -b force-color-display`
4. Make your code changes above, `git add <file> <file> <file> ...` and then `git commit -m 'Fix #9: Add support for differing BitsPerPixel and Depth settings'`
5. Push this branch up to your github repo: `git push origin force-color-display`
6. Go to your repo page and it should pop-up a yellow box saying you have a recently added branch, and allow you to create a Pull Request against my repo's `master` branch

Forgive me if you already knew this, but in case not, that's that the typical workflow with git/github.  Let me know if anything is unclear.

**Comment by zzincubus** [comment]
@humphd done and thank you very much for the instructions. I forgot there is also a change to support RealVNC 4.0 server on Linux (only version number check and force protocol to 3.8).

**Comment by humphd** [comment]
OK, can you add a comment to that effect in the code where you're doing that?  Thanks.

@Fabzien or @gashlin, would either of you be willing to test @zzincubus's changes at https://github.com/humphd/VncSharp/pull/29?
